export const DEFAULT = "default";

export const CONTROLLER_METADATA = "CONTROLLER";
export const HTTP_METHOD_METADATA = "HTTP_METHOD";
export const HTTP_REQUEST_METADATA = "HTTP_REQUEST";

export const INTERCEPTORS_CONTROLLER_METADATA = "INTERCEPTORS_CONTROLLER";
export const INTERCEPTORS_ROUTER_METADATA = "INTERCEPTORS_ROUTER";

export const GUARDIAN_CONTROLLER_METADATA = "GUARDIAN_CONTROLLER";
export const GUARDIAN_ROUTER_METADATA = "GUARDIAN_ROUTER";

export const POLICY_CONTROLLER_METADATA = "POLICY_CONTROLLER";
export const POLICY_ROUTER_METADATA = "POLICY_ROUTER";

export enum HttpMethods {
	GET = "get",
	POST = "post",
	PUT = "put",
	PATCH = "patch",
	DELETE = "delete",
}

export enum RequestInformation {
	PARAMS = "params",
	QUERY = "query",
	BODY = "body",
	HEADERS = "headers",
	USER = "user",
	FILE = "file",
}

export enum HttpStatusCode {
	OK = 200,
	CREATED = 201,
	NO_CONTENT = 204,
	NOT_FOUND = 404,
	INTERNAL_SERVER_ERROR = 500,
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	CONFLICT = 409,
	UNPROCESSABLE_ENTITY = 422,
	BAD_GATEWAY = 502,
	SERVICE_UNAVAILABLE = 503,
	GATEWAY_TIMEOUT = 504,
	HTTP_VERSION_NOT_SUPPORTED = 505,
	INSUFFICIENT_STORAGE = 507,
	LOOP_DETECTED = 508,
	NOT_EXTENDED = 510,
	NETWORK_AUTHENTICATION_REQUIRED = 511,
	UNSUPPORTED_MEDIA_TYPE = 415,
	TOO_MANY_REQUESTS = 429,
	REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	UNAVAILABLE_FOR_LEGAL_REASONS = 451,
	NOT_IMPLEMENTED = 501,
}
